name: tomo_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  fab_circular_menu: ^1.0.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^0.5.7
  url_launcher: ^5.4.2
  http: ^0.13.3
  flutter_facebook_login: ^2.0.1
  #flutter_facebook_login: ^3.0.0
  google_sign_in: "^4.5.1"
  permission_handler: ^5.1.0+2
  cached_network_image: ^3.0.0
  agora_rtc_engine: ^3.2.1
  agora_rtm: ^0.9.14
  random_color: ^1.0.5
  font_awesome_flutter: 8.8.1
  image_picker: ^0.7.5+2
  audio_service: ^0.17.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  image: ^3.0.2
  geolocator: ^6.1.13
  intl: 0.17.0
  bloc: ^6.0.2
  flutter_bloc: ^6.0.1
  connectivity: ^3.0.3
  webview_flutter: ^2.0.7
  http_auth: ^1.0.0
  flutter_braintree: ^0.5.3+1
  need_resume: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/sample.png
    - assets/nounmusic.png
    - assets/facebook.png
    - assets/twitter.png
    - assets/directorchair.png
    - assets/audience.png
    - assets/audience.png
    - assets/popular.png
    - assets/hot.png
    - assets/filter.png
    - assets/addtocart.png
    - assets/shops.png
    - assets/visa.png
    - assets/mastercard.png
    - assets/amex.png




